M48
; DRILL file {KiCad 6.0.8-f2edbf62ab~116~ubuntu20.04.1} date Mi 02 Aug 2023 22:58:12 CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-02T22:58:12+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.8-f2edbf62ab~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.500
%
G90
G05
T1
X39.5Y-25.5
X100.5Y-25.5
X202.5Y-25.5
T2
X83.1Y-102.7
X93.6Y-102.7
T3
X151.892Y-64.834
T0
M30
